--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-05-24 09:33:30

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4850 (class 1262 OID 16398)
-- Name: coffee; Type: DATABASE; Schema: -; Owner: coffee
--

CREATE DATABASE coffee WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Spanish_Colombia.1252';


ALTER DATABASE coffee OWNER TO coffee;

\connect coffee

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4851 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16400)
-- Name: coffee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.coffee (
    id integer NOT NULL,
    name character varying(100),
    origin_country integer
);


ALTER TABLE public.coffee OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16418)
-- Name: coffee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.coffee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coffee_id_seq
    START WITH 4
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16405)
-- Name: country; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.country (
    id integer NOT NULL,
    name character varying(100)
);


ALTER TABLE public.country OWNER TO postgres;

--
-- TOC entry 4842 (class 0 OID 16400)
-- Dependencies: 215
-- Data for Name: coffee; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.coffee VALUES (2, 'Caturra', 1);
INSERT INTO public.coffee VALUES (3, 'Arabica', 2);
INSERT INTO public.coffee VALUES (4, 'Tabi', 1);
INSERT INTO public.coffee VALUES (1, 'Java', 3);


--
-- TOC entry 4843 (class 0 OID 16405)
-- Dependencies: 216
-- Data for Name: country; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.country VALUES (1, 'Colombia');
INSERT INTO public.country VALUES (2, 'Brasil');
INSERT INTO public.country VALUES (3, 'India');


--
-- TOC entry 4852 (class 0 OID 0)
-- Dependencies: 217
-- Name: coffee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.coffee_id_seq', 4, true);


--
-- TOC entry 4693 (class 2606 OID 16404)
-- Name: coffee coffee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coffee
    ADD CONSTRAINT coffee_pkey PRIMARY KEY (id);


--
-- TOC entry 4695 (class 2606 OID 16409)
-- Name: country country_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT country_pkey PRIMARY KEY (id);


--
-- TOC entry 4697 (class 2606 OID 16411)
-- Name: country name_ukey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT name_ukey UNIQUE (name) INCLUDE (name);


--
-- TOC entry 4698 (class 2606 OID 16412)
-- Name: coffee origin_country_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coffee
    ADD CONSTRAINT origin_country_fk FOREIGN KEY (origin_country) REFERENCES public.country(id) NOT VALID;


--
-- TOC entry 4853 (class 0 OID 0)
-- Dependencies: 4698
-- Name: CONSTRAINT origin_country_fk ON coffee; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON CONSTRAINT origin_country_fk ON public.coffee IS 'Llave foránea para el país de origen del café';


-- Completed on 2024-05-24 09:33:31

--
-- PostgreSQL database dump complete
--

